export { SEO } from './SEO/SEO'
export { Navbar } from './Navbar/Navbar'
export { SectionTitle } from './SectionTitle/SectionTitle'
export { ButtonWrap } from './ButtonWrap/ButtonWrap'
export { ContentWrap } from './ContentWrap/ContentWrap'
